[environments.staging]
store = "safat-test.myshopify.com"
theme = "154613514287"

[environments.production]
store = "safat-test.myshopify.com"
theme = "127783108655"

[environments.content]
store = "safat-test.myshopify.com"
theme = "153854509103"

[environments.default]
store = "safat-test.myshopify.com"
theme = "154613514287"