[environments.staging]
store = "safat-test.myshopify.com"
theme = "153815679023"

[environments.production]
store = "safat-test.myshopify.com"
theme = "127783108655"

[environments.default]
store = "safat-test.myshopify.com"
theme = "153815679023"