[environments.staging]
store = "safat-test.myshopify.com"
theme = "154614956079"

[environments.production]
store = "safat-test.myshopify.com"
theme = "154614988847"

[environments.content]
store = "safat-test.myshopify.com"
theme = "153854509103"

[environments.default]
store = "safat-test.myshopify.com"
theme = "154614956079"
